# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_number.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Set_number(object):
    def setupUi(self, Set_number):
        Set_number.setObjectName("Set_number")
        Set_number.resize(510, 533)
        Set_number.setMinimumSize(QtCore.QSize(510, 533))
        Set_number.setMaximumSize(QtCore.QSize(510, 533))
        Set_number.setModal(True)
        self.frame = QtWidgets.QFrame(Set_number)
        self.frame.setGeometry(QtCore.QRect(110, 10, 321, 80))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_number = QtWidgets.QLabel(self.frame)
        self.label_number.setGeometry(QtCore.QRect(10, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_number.setFont(font)
        self.label_number.setText("")
        self.label_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_number.setObjectName("label_number")
        self.pushButton = QtWidgets.QPushButton(Set_number)
        self.pushButton.setGeometry(QtCore.QRect(40, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Set_number)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Set_number)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Set_number)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 210, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Set_number)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 210, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Set_number)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 210, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Set_number)
        self.pushButton_7.setGeometry(QtCore.QRect(40, 320, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Set_number)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 320, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Set_number)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 320, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Set_number)
        self.pushButton_10.setGeometry(QtCore.QRect(370, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Set_number)
        self.pushButton_11.setGeometry(QtCore.QRect(370, 210, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Set_number)
        self.pushButton_12.setGeometry(QtCore.QRect(370, 320, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_14 = QtWidgets.QPushButton(Set_number)
        self.pushButton_14.setGeometry(QtCore.QRect(150, 430, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.btn_dot = QtWidgets.QPushButton(Set_number)
        self.btn_dot.setGeometry(QtCore.QRect(260, 430, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_dot.setFont(font)
        self.btn_dot.setObjectName("btn_dot")
        self.pushButton_16 = QtWidgets.QPushButton(Set_number)
        self.pushButton_16.setGeometry(QtCore.QRect(370, 430, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_number_unit = QtWidgets.QLabel(Set_number)
        self.label_number_unit.setGeometry(QtCore.QRect(440, 20, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_number_unit.setFont(font)
        self.label_number_unit.setText("")
        self.label_number_unit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_unit.setObjectName("label_number_unit")
        self.label_number_zone = QtWidgets.QLabel(Set_number)
        self.label_number_zone.setGeometry(QtCore.QRect(10, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_number_zone.setFont(font)
        self.label_number_zone.setText("")
        self.label_number_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_zone.setObjectName("label_number_zone")

        self.retranslateUi(Set_number)
        self.pushButton.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_3.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_2.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_4.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_6.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_5.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_7.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_8.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_9.clicked.connect(Set_number.click_num) # type: ignore
        self.btn_dot.clicked.connect(Set_number.click_dot) # type: ignore
        self.pushButton_14.clicked.connect(Set_number.click_num) # type: ignore
        self.pushButton_10.clicked.connect(Set_number.click_num_back) # type: ignore
        self.pushButton_11.clicked.connect(Set_number.click_num_clear) # type: ignore
        self.pushButton_12.clicked.connect(Set_number.set_num_save) # type: ignore
        self.pushButton_16.clicked.connect(Set_number.set_cancel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Set_number)

    def retranslateUi(self, Set_number):
        _translate = QtCore.QCoreApplication.translate
        Set_number.setWindowTitle(_translate("Set_number", "Dialog"))
        self.pushButton.setText(_translate("Set_number", "1"))
        self.pushButton_2.setText(_translate("Set_number", "3"))
        self.pushButton_3.setText(_translate("Set_number", "2"))
        self.pushButton_4.setText(_translate("Set_number", "4"))
        self.pushButton_5.setText(_translate("Set_number", "6"))
        self.pushButton_6.setText(_translate("Set_number", "5"))
        self.pushButton_7.setText(_translate("Set_number", "7"))
        self.pushButton_8.setText(_translate("Set_number", "8"))
        self.pushButton_9.setText(_translate("Set_number", "9"))
        self.pushButton_10.setText(_translate("Set_number", "<-X"))
        self.pushButton_11.setText(_translate("Set_number", "<지움>"))
        self.pushButton_12.setText(_translate("Set_number", "<확인>"))
        self.pushButton_14.setText(_translate("Set_number", "0"))
        self.btn_dot.setText(_translate("Set_number", "."))
        self.pushButton_16.setText(_translate("Set_number", "<취소>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Set_number = QtWidgets.QDialog()
    ui = Ui_Set_number()
    ui.setupUi(Set_number)
    Set_number.show()
    sys.exit(app.exec_())
