# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_irrigation_time.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Set_irrigation_time(object):
    def setupUi(self, Set_irrigation_time):
        Set_irrigation_time.setObjectName("Set_irrigation_time")
        Set_irrigation_time.resize(530, 533)
        Set_irrigation_time.setMinimumSize(QtCore.QSize(530, 533))
        Set_irrigation_time.setMaximumSize(QtCore.QSize(530, 533))
        Set_irrigation_time.setModal(True)
        self.btn_1 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_1.setGeometry(QtCore.QRect(10, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_2.setGeometry(QtCore.QRect(140, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_3.setGeometry(QtCore.QRect(270, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_4.setGeometry(QtCore.QRect(400, 10, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_5.setGeometry(QtCore.QRect(10, 140, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_6.setGeometry(QtCore.QRect(140, 140, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_7.setGeometry(QtCore.QRect(270, 140, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_8.setGeometry(QtCore.QRect(400, 140, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_10 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_10.setGeometry(QtCore.QRect(140, 270, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_10.setFont(font)
        self.btn_10.setObjectName("btn_10")
        self.btn_11 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_11.setGeometry(QtCore.QRect(270, 270, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_11.setFont(font)
        self.btn_11.setObjectName("btn_11")
        self.btn_12 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_12.setGeometry(QtCore.QRect(400, 270, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_12.setFont(font)
        self.btn_12.setObjectName("btn_12")
        self.btn_9 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_9.setGeometry(QtCore.QRect(10, 270, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.btn_13 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_13.setGeometry(QtCore.QRect(10, 400, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_13.setFont(font)
        self.btn_13.setObjectName("btn_13")
        self.btn_cancel = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_cancel.setGeometry(QtCore.QRect(400, 400, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_14 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_14.setGeometry(QtCore.QRect(140, 400, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_14.setFont(font)
        self.btn_14.setObjectName("btn_14")
        self.btn_15 = QtWidgets.QPushButton(Set_irrigation_time)
        self.btn_15.setGeometry(QtCore.QRect(270, 400, 121, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.btn_15.setFont(font)
        self.btn_15.setObjectName("btn_15")

        self.retranslateUi(Set_irrigation_time)
        self.btn_1.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_2.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_3.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_4.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_5.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_6.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_7.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_8.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_9.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_10.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_11.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_12.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_13.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_14.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_15.clicked.connect(Set_irrigation_time.click_num) # type: ignore
        self.btn_cancel.clicked.connect(Set_irrigation_time.click_cancel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Set_irrigation_time)

    def retranslateUi(self, Set_irrigation_time):
        _translate = QtCore.QCoreApplication.translate
        Set_irrigation_time.setWindowTitle(_translate("Set_irrigation_time", "Dialog"))
        self.btn_1.setText(_translate("Set_irrigation_time", "1"))
        self.btn_2.setText(_translate("Set_irrigation_time", "2"))
        self.btn_3.setText(_translate("Set_irrigation_time", "3"))
        self.btn_4.setText(_translate("Set_irrigation_time", "4"))
        self.btn_5.setText(_translate("Set_irrigation_time", "5"))
        self.btn_6.setText(_translate("Set_irrigation_time", "6"))
        self.btn_7.setText(_translate("Set_irrigation_time", "7"))
        self.btn_8.setText(_translate("Set_irrigation_time", "8"))
        self.btn_10.setText(_translate("Set_irrigation_time", "10"))
        self.btn_11.setText(_translate("Set_irrigation_time", "11"))
        self.btn_12.setText(_translate("Set_irrigation_time", "12"))
        self.btn_9.setText(_translate("Set_irrigation_time", "9"))
        self.btn_13.setText(_translate("Set_irrigation_time", "13"))
        self.btn_cancel.setText(_translate("Set_irrigation_time", "취소"))
        self.btn_14.setText(_translate("Set_irrigation_time", "14"))
        self.btn_15.setText(_translate("Set_irrigation_time", "15"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Set_irrigation_time = QtWidgets.QDialog()
    ui = Ui_Set_irrigation_time()
    ui.setupUi(Set_irrigation_time)
    Set_irrigation_time.show()
    sys.exit(app.exec_())
